### ISSUE TITLE
Validation rules

### ISSUE THREAD

**Issue by paritosh-gupta** [ac3433/CS451-Checker#3]
Please mention all the validation rules here. Check mark ones that have been completed.
If a move is in-valid return an object with the properties
```json
{
"isvalid":false,
"reason" : " validation reason here"
} 
```
else
```json
{
"isvalid":true,
"reason" : " "
} 
```

**Comment by zg56** [comment]
validation functions:
winCheckByCapture - checks if opponents pieces are all missing
winningCheckForBlocks - checks if opponents pieces are all blocked and can't move anymore
winningCheckFor Kings - checks if the king pieces can make a move still since they can move backwards as well
mandatoryCapture - checks if Player 1 can make a capture on the board
mandatoryCapturePlayer2 - checks if Player 2 can make a capture on the board
multipleCaptureForward - checks if player 1 can make a multiple capture
multipleCaptureBackward - checks if player 2 can make a multiple capture
multipleCaptureKing - checks if a king piece can make multiple captures on the board
kinging - changes the piece into a king piece
validateMovement - returns an array where the first element is a boolean depending if the move was valid or not. second element is a string explaining the reason why the move was not valid.
